package com.Backend.Backend.RepositoryTest;





import com.Backend.Backend.Models.Match;
import com.Backend.Backend.Models.Match_formats.Kabaddi.Kabaddi_match;
import com.Backend.Backend.Repository.MatchRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

@DataMongoTest
public class Kabaddi_match_test {
    @Autowired
    private MatchRepository matchRepository;
    @BeforeEach
    void clean() {
        matchRepository.deleteAll();
    }
    @Test
    void testKabaddiPersistenceAndInheritance() {
        // 1. Arrange: Create a KabaddiMatch
        Kabaddi_match match = new Kabaddi_match();

        match.setStartTime(LocalDateTime.now().plusDays(1));
        match.setTeamAId("COLLEGE_A_TEAM");
        match.setTeamBId("COLLEGE_B_TEAM");

        // Kabaddi specific fields
        match.setPointsB(5);
        match.setPointsA(10);
        match.setHalf(1);

        // 2. Act: Save to MongoDB
        Kabaddi_match savedMatch = matchRepository.save(match);

        // 3. Assert: Verify everything is correct
        assertNotNull(savedMatch.getId(), "ID should be generated by MongoDB");




        // 4. Verify Polymorphism: Retrieve it as the base class 'Match'
        Match retrieved = matchRepository.findById(savedMatch.getId()).orElse(null);
        assertTrue(retrieved instanceof Kabaddi_match, "Should be castable back to KabaddiMatch");
    }



}
