package com.Backend.Backend.RepositoryTest;

import com.Backend.Backend.Models.Users;
import com.Backend.Backend.Repository.UserRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@DataMongoTest
public class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Test
    @DisplayName("Test: Insert a single user into gusto_db")
    void testInsertUser() {
        // 1. Create the object
        Users user = new Users();
        user.setUsername("gusto_tester");
        user.setEmail("test@gusto.com");
        user.setSport("Football");

        // 2. Insert into database
        Users savedUser = userRepository.save(user);

        // 3. Verify (Systematic Check)
        // Check that the ID was generated by MongoDB
        assertNotNull(savedUser.getId());

        // Check that the data matches
        assertEquals("gusto_tester", savedUser.getUsername());

        System.out.println("Successfully inserted user with ID: " + savedUser.getId());
    }
}